export interface Verein {
  id: string;
  name: string;
  kanton: string;
  ortschaft: string;
  disziplinen: string[];
  website?: string;
  email?: string;
  neumitglieder?: boolean;
  beschreibung?: string;
  lat: number;
  lng: number;
}

export const VEREINE: Verein[] = [
  // ─── KANTON BERN ────────────────────────────────────────
  {
    id: "be-1",
    name: "Stadtschützen Bern",
    kanton: "BE",
    ortschaft: "Bern",
    disziplinen: ["300m", "Pistole", "50m"],
    website: "https://www.stadtschuetzen-bern.ch",
    neumitglieder: true,
    beschreibung: "Gegründet 1818. Eine der ältesten Schützengesellschaften der Bundesstadt mit Gewehr 300m, Pistole und 50m.",
    lat: 46.948,
    lng: 7.447,
  },
  {
    id: "be-2",
    name: "Stadtschützen Thun",
    kanton: "BE",
    ortschaft: "Thun",
    disziplinen: ["300m", "Pistole", "Feldschiessen"],
    website: "https://www.stadtschuetzen-thun.ch",
    neumitglieder: true,
    beschreibung: "Grösste Schützengesellschaft im Raum Thun. Aktiver Verein mit Gewehr- und Pistolenschiessen.",
    lat: 46.758,
    lng: 7.628,
  },
  {
    id: "be-3",
    name: "Infanterieschützen Bern",
    kanton: "BE",
    ortschaft: "Bern",
    disziplinen: ["300m", "Feldschiessen"],
    website: "https://www.infanterieschuetzenbern.ch",
    neumitglieder: true,
    beschreibung: "Traditionsverein in Bern mit Schwerpunkt Gewehr 300m und Feldschiessen.",
    lat: 46.948,
    lng: 7.447,
  },
  {
    id: "be-4",
    name: "Militärschützen Thun",
    kanton: "BE",
    ortschaft: "Thun",
    disziplinen: ["300m", "Feldschiessen"],
    website: "https://www.militärschützen-thun.ch",
    neumitglieder: true,
    beschreibung: "Militärschützenverein in Thun mit aktivem Schiessbetrieb und Jugendförderung.",
    lat: 46.758,
    lng: 7.628,
  },
  {
    id: "be-5",
    name: "Feldschützen Lauenen-Thun",
    kanton: "BE",
    ortschaft: "Thun",
    disziplinen: ["300m", "Feldschiessen"],
    website: "https://www.fslauenenthun.ch",
    neumitglieder: true,
    beschreibung: "Dynamischer Schützenverein mit Schiessanlage Guntelsey in Thun. Fördert Jungschützenkurse und betreut schiesspflichtige Militärpersonen.",
    lat: 46.758,
    lng: 7.628,
  },
  {
    id: "be-6",
    name: "SG Strättligen Thun",
    kanton: "BE",
    ortschaft: "Thun",
    disziplinen: ["300m"],
    website: "https://www.sgstraettligen.ch",
    neumitglieder: true,
    beschreibung: "Gegründet 1889. Traditionsreiche Schützengesellschaft aus der Region Thun mit starkem Engagement in der Jungschützenausbildung.",
    lat: 46.743,
    lng: 7.618,
  },
  {
    id: "be-7",
    name: "Schützengesellschaft Burgdorf",
    kanton: "BE",
    ortschaft: "Burgdorf",
    disziplinen: ["300m", "Pistole"],
    neumitglieder: true,
    beschreibung: "Gegründet 1534 als Burgerliche Schützengesellschaft — eine der ältesten Schützengesellschaften der Schweiz.",
    lat: 47.059,
    lng: 7.628,
  },
  {
    id: "be-8",
    name: "Schützen Thunbachtal",
    kanton: "BE",
    ortschaft: "Thun",
    disziplinen: ["300m"],
    website: "https://www.schuetzen-thunbachtal.ch",
    neumitglieder: true,
    beschreibung: "2019 aus der Fusion der SG Lustdorf und SG Thundorf entstanden. Trainiert auf der Schiesslage Thundorf (300m) mit Feldschiessen und Jungschützenkursen.",
    lat: 46.765,
    lng: 7.645,
  },

  // ─── KANTON ZÜRICH ──────────────────────────────────────
  {
    id: "zh-1",
    name: "Schützengesellschaft der Stadt Zürich (SGZ)",
    kanton: "ZH",
    ortschaft: "Zürich",
    disziplinen: ["300m", "Pistole", "50m", "Luftgewehr"],
    website: "https://www.sgz.ch",
    neumitglieder: true,
    beschreibung: "Traditionsreiche Schützengesellschaft der Stadt Zürich. Organisiert u.a. das Knabenschiessen. Disziplinen: Gewehr 300m, Pistole, 50m, Luftgewehr.",
    lat: 47.362,
    lng: 8.530,
  },
  {
    id: "zh-2",
    name: "Stadtschützen Winterthur",
    kanton: "ZH",
    ortschaft: "Winterthur",
    disziplinen: ["300m", "Pistole"],
    website: "https://www.stadtsw.ch",
    neumitglieder: true,
    beschreibung: "2007 aus der Fusion der Schützengesellschaft Winterthur und der Schützensektion des Stadtturnvereins entstanden. Aktive Jugendförderung.",
    lat: 47.500,
    lng: 8.724,
  },
  {
    id: "zh-3",
    name: "Feldschützengesellschaft Winterthur (FSGW)",
    kanton: "ZH",
    ortschaft: "Winterthur",
    disziplinen: ["300m", "Feldschiessen"],
    website: "https://www.fsgw.ch",
    neumitglieder: true,
    beschreibung: "Traditionsreicher Feldschützenverein mit Schiessanlage Ohrbühl, einer der grössten und modernsten Anlagen im Kanton Zürich.",
    lat: 47.500,
    lng: 8.724,
  },
  {
    id: "zh-4",
    name: "Standschützen Neumünster (SSGN)",
    kanton: "ZH",
    ortschaft: "Zürich",
    disziplinen: ["300m", "Pistole"],
    website: "https://www.ssgn.ch",
    neumitglieder: true,
    beschreibung: "1895 von dreizehn Riesbacher Schützen gegründet. Breites Disziplinenangebot: Gewehr 300m/50m/10m und Pistole 50m/25m/10m im Schiesssportzentrum Höngg.",
    lat: 47.357,
    lng: 8.556,
  },
  {
    id: "zh-5",
    name: "Pistolenschützen Zürich-Affoltern",
    kanton: "ZH",
    ortschaft: "Zürich",
    disziplinen: ["Pistole", "25m"],
    website: "https://psza.ch",
    neumitglieder: true,
    beschreibung: "Familiärer Pistolenverein mit rund 30 Mitgliedern im Schiessstand Hürstwald. Training jeweils mittwochs, ergänzt durch das jährliche Winterschiessen.",
    lat: 47.422,
    lng: 8.512,
  },
  {
    id: "zh-6",
    name: "Schützenverein Zürich-Leimbach (SVZL)",
    kanton: "ZH",
    ortschaft: "Zürich",
    disziplinen: ["300m"],
    website: "https://www.svzl.ch",
    neumitglieder: true,
    beschreibung: "1895 gegründet, im Sihltal verwurzelt. Schiesst auf der traditionsreichen Schiessanlage Albisgütli mit Gewehr 300m und Pistole 25m.",
    lat: 47.335,
    lng: 8.519,
  },
  {
    id: "zh-7",
    name: "Pistolenschützen Bubikon",
    kanton: "ZH",
    ortschaft: "Bubikon",
    disziplinen: ["Pistole", "25m"],
    website: "https://pistolenschuetzen-bubikon.ch",
    neumitglieder: true,
    beschreibung: "1939 gegründet, seit 2000 eigenständig. Schiesst auf der Anlage GESA Betzholz im Zürcher Oberland, bekannt für Revolvermeisterschaften.",
    lat: 47.267,
    lng: 8.818,
  },
  {
    id: "zh-8",
    name: "Schiesssportverein Wehntal",
    kanton: "ZH",
    ortschaft: "Niederweningen",
    disziplinen: ["Pistole", "IPSC", "IDPA"],
    website: "https://ssv-wehntal.clubdesk.ch",
    neumitglieder: true,
    beschreibung: "Dynamischer Schiessverein mit IPSC- und IDPA-Sektion im Zürcher Unterland.",
    lat: 47.498,
    lng: 8.366,
  },
  {
    id: "zh-9",
    name: "Schützengesellschaft Züri 9",
    kanton: "ZH",
    ortschaft: "Zürich",
    disziplinen: ["300m", "Pistole"],
    website: "https://www.sg-zueri9.ch",
    neumitglieder: true,
    beschreibung: "Gegründet 1874. Betreibt die moderne Schiessanlage Hasenrain mit 25/50m- und 300m-Ständen nach neusten Umweltstandards.",
    lat: 47.389,
    lng: 8.488,
  },
  {
    id: "zh-10",
    name: "Sportschützen Glattfelden",
    kanton: "ZH",
    ortschaft: "Glattfelden",
    disziplinen: ["300m", "Pistole", "50m"],
    neumitglieder: true,
    beschreibung: "1950 als Kleinkaliber-Sektion Glattfelden gegründet. Schiesst auf der 50m-Anlage Buechhalde, vorbildliche Jugendförderung mit J+S-Kursen.",
    lat: 47.481,
    lng: 8.511,
  },

  // ─── KANTON LUZERN ──────────────────────────────────────
  {
    id: "lu-1",
    name: "Stadtschützen Luzern",
    kanton: "LU",
    ortschaft: "Luzern",
    disziplinen: ["300m", "Pistole", "50m"],
    website: "https://stadtschuetzen-luzern.ch",
    neumitglieder: true,
    beschreibung: "Nachfolgerin einer Schützengesellschaft, die seit 1429 dokumentiert ist. Betreibt das Luzern Indoor Schiesssportzentrum.",
    lat: 47.050,
    lng: 8.309,
  },
  {
    id: "lu-2",
    name: "Feldschützenverein Luzern (FSVL)",
    kanton: "LU",
    ortschaft: "Luzern",
    disziplinen: ["300m", "Pistole", "50m", "Luftgewehr"],
    website: "http://www.feldschuetzen-luzern.ch",
    neumitglieder: true,
    beschreibung: "Breites Angebot: Luftpistole/-gewehr 10m, Pistole 25/50m, Gewehr 300m. Historisches Schiessen und externe Wettkämpfe.",
    lat: 47.050,
    lng: 8.309,
  },
  {
    id: "lu-3",
    name: "Gesellschaft Herren zu Schützen",
    kanton: "LU",
    ortschaft: "Luzern",
    disziplinen: ["300m", "Pistole"],
    website: "https://www.herrenzuschuetzen.ch",
    neumitglieder: true,
    beschreibung: "Historische Schützengesellschaft in Luzern mit langer Tradition.",
    lat: 47.050,
    lng: 8.309,
  },

  // ─── KANTON ST. GALLEN ─────────────────────────────────
  {
    id: "sg-1",
    name: "Feldschützen-Gesellschaft der Stadt St. Gallen",
    kanton: "SG",
    ortschaft: "St. Gallen",
    disziplinen: ["300m", "Feldschiessen"],
    website: "https://www.feldsg.ch",
    neumitglieder: true,
    beschreibung: "Gegründet 1850. Traditionsreiche Feldschützengesellschaft der Stadt St. Gallen.",
    lat: 47.425,
    lng: 9.377,
  },
  {
    id: "sg-2",
    name: "Schiesszentrum Ostschweiz",
    kanton: "SG",
    ortschaft: "St. Gallen",
    disziplinen: ["Pistole", "300m", "IPSC"],
    website: "https://szo.swiss",
    neumitglieder: true,
    beschreibung: "Modernes Schiesszentrum in der Ostschweiz mit breitem Disziplinenangebot.",
    lat: 47.414,
    lng: 9.339,
  },
  {
    id: "sg-3",
    name: "Dynamic Shooting Ostschweiz (DSO)",
    kanton: "SG",
    ortschaft: "St. Gallen",
    disziplinen: ["IPSC"],
    website: "https://dso.swiss",
    neumitglieder: true,
    beschreibung: "2017 gegründeter Verein für dynamisches Schiessen nach IPSC-Standards in der Ostschweiz.",
    lat: 47.425,
    lng: 9.377,
  },

  // ─── KANTON AARGAU ──────────────────────────────────────
  {
    id: "ag-1",
    name: "Feldschützengesellschaft Aarau",
    kanton: "AG",
    ortschaft: "Aarau",
    disziplinen: ["300m", "Feldschiessen"],
    neumitglieder: true,
    beschreibung: "Traditionsverein in Aarau, der Gründungsstadt des SSV (1824).",
    lat: 47.393,
    lng: 8.044,
  },
  {
    id: "ag-2",
    name: "Sportschützen Falke",
    kanton: "AG",
    ortschaft: "Aargau",
    disziplinen: ["Pistole", "IPSC", "300m"],
    website: "https://www.sportschuetzen-falke.ch",
    neumitglieder: true,
    beschreibung: "Sportschützenverein mit IPSC-Sektion. Vielfältiges Angebot.",
    lat: 47.420,
    lng: 8.252,
  },
  {
    id: "ag-3",
    name: "Schützenverein Baden",
    kanton: "AG",
    ortschaft: "Baden",
    disziplinen: ["300m", "Pistole"],
    neumitglieder: true,
    beschreibung: "Schützengesellschaft der Stadt Baden mit Gewehr, Pistole und Luftpistole. Teil des Aargauischen Schiesssportverbands.",
    lat: 47.474,
    lng: 8.306,
  },

  // ─── KANTON BASEL ───────────────────────────────────────
  {
    id: "bs-1",
    name: "Scharfschützen-Gesellschaft Basel",
    kanton: "BS",
    ortschaft: "Basel",
    disziplinen: ["300m", "Pistole", "Luftgewehr", "Feldschiessen"],
    website: "https://www.scharfschuetzen-basel.ch",
    neumitglieder: true,
    beschreibung: "Über 100 Jahre Geschichte. Disziplinen: Gewehr 300m, Pistole 25m, Luftgewehr 10m, Obligatorisches und Feldschiessen.",
    lat: 47.560,
    lng: 7.589,
  },
  {
    id: "bs-2",
    name: "Schiess-Sport Helvetia Basel",
    kanton: "BS",
    ortschaft: "Basel",
    disziplinen: ["300m", "Pistole", "Luftgewehr"],
    website: "https://www.sp-helvetia.ch",
    neumitglieder: true,
    beschreibung: "2012 aus der Fusion von Schiesserverein Helvetia Basel 1883 und Sportschützen Helvetia Basel 1941 entstanden. Grösstes Angebot an Schiesssportdisziplinen in Basel-Stadt.",
    lat: 47.560,
    lng: 7.589,
  },

  // ─── KANTON BASEL-LANDSCHAFT ────────────────────────────
  {
    id: "bl-1",
    name: "Sportschützen Oberwil BL",
    kanton: "BL",
    ortschaft: "Oberwil",
    disziplinen: ["300m", "Pistole"],
    website: "https://www.sportschuetzen-oberwil.ch",
    neumitglieder: true,
    beschreibung: "Sportschützenverein aus Oberwil im Baselbiet mit Kleinkaliber 50m und Luftgewehr 10m, elektronischen Trefferanzeigen und J+S-Kursen.",
    lat: 47.511,
    lng: 7.554,
  },
  {
    id: "bl-2",
    name: "Schützenverein Liestal",
    kanton: "BL",
    ortschaft: "Liestal",
    disziplinen: ["300m", "Pistole"],
    neumitglieder: true,
    beschreibung: "Gegründet 1824. Eine der ältesten Organisationen der Stadt Liestal mit Gewehr-, Pistolen- und Jungschützenprogrammen auf der Schiessanlage Sichtern.",
    lat: 47.484,
    lng: 7.735,
  },

  // ─── KANTON SOLOTHURN ───────────────────────────────────
  {
    id: "so-1",
    name: "Feldschützen Solothurn",
    kanton: "SO",
    ortschaft: "Solothurn",
    disziplinen: ["300m", "Feldschiessen"],
    neumitglieder: true,
    beschreibung: "Traditionsreicher Feldschützenverein in Solothurn, der den Gewehrschiesssport auf 300m pflegt. Angeschlossen an den Solothurner Schiesssportverband.",
    lat: 47.209,
    lng: 7.532,
  },
  {
    id: "so-2",
    name: "Schützenverein Olten",
    kanton: "SO",
    ortschaft: "Olten",
    disziplinen: ["300m", "Pistole"],
    neumitglieder: true,
    beschreibung: "Gegründet 1488. Einer der ältesten Vereine der Stadt Olten mit über 500-jähriger Schiesstradition.",
    lat: 47.350,
    lng: 7.907,
  },

  // ─── KANTON FREIBURG ────────────────────────────────────
  {
    id: "fr-1",
    name: "Société de tir de Fribourg",
    kanton: "FR",
    ortschaft: "Fribourg",
    disziplinen: ["300m", "Pistole"],
    neumitglieder: true,
    beschreibung: "Gegründet 1493. Ältester Sportverein des Kantons Freiburg mit rund 140 Mitgliedern von 16 bis 85 Jahren.",
    lat: 46.807,
    lng: 7.162,
  },
  {
    id: "fr-2",
    name: "Feldschützen Murten",
    kanton: "FR",
    ortschaft: "Murten",
    disziplinen: ["300m"],
    neumitglieder: true,
    beschreibung: "Um 1824 gegründet. Pflegt Schiesssport und historische Traditionen im Seebezirk, schiesst auf der Anlage Jägerstein in Galmiz.",
    lat: 46.929,
    lng: 7.118,
  },

  // ─── KANTON WALLIS ──────────────────────────────────────
  {
    id: "vs-1",
    name: "Société de tir de Sion",
    kanton: "VS",
    ortschaft: "Sion",
    disziplinen: ["300m", "Pistole"],
    neumitglieder: true,
    beschreibung: "Gegründet 1599 als Cible de Sion. Älteste und grösste Schützengesellschaft des Kantons Wallis mit über 400-jähriger Tradition.",
    lat: 46.233,
    lng: 7.360,
  },
  {
    id: "vs-2",
    name: "Schützenverein Brig",
    kanton: "VS",
    ortschaft: "Brig",
    disziplinen: ["300m"],
    neumitglieder: true,
    beschreibung: "Historische Stadtschützengesellschaft Brig, fusioniert mit weiteren Vereinen zum Schiessport-Zentrum Chalchofen in der Region Brig-Glis.",
    lat: 46.315,
    lng: 7.988,
  },

  // ─── KANTON GRAUBÜNDEN ──────────────────────────────────
  {
    id: "gr-1",
    name: "Schützengesellschaft der Stadt Chur",
    kanton: "GR",
    ortschaft: "Chur",
    disziplinen: ["300m", "Pistole"],
    website: "https://www.sg-chur.ch",
    neumitglieder: true,
    beschreibung: "Schützengesellschaft der Bündner Hauptstadt mit Gewehr- und Pistolenschiessen.",
    lat: 46.851,
    lng: 9.531,
  },
  {
    id: "gr-2",
    name: "Feldschützen Davos",
    kanton: "GR",
    ortschaft: "Davos",
    disziplinen: ["300m"],
    neumitglieder: true,
    beschreibung: "Historischer Schützenverein in Davos, 2004 mit weiteren Vereinen zum Verein Schiess-Sport Davos fusioniert. Schiesst auf modernen Anlagen mit elektronischer Trefferanzeige.",
    lat: 46.800,
    lng: 9.836,
  },

  // ─── KANTON TESSIN ──────────────────────────────────────
  {
    id: "ti-1",
    name: "Società di tiro Lugano",
    kanton: "TI",
    ortschaft: "Lugano",
    disziplinen: ["300m", "Pistole"],
    neumitglieder: true,
    beschreibung: "Gegründet 1832 als Civici Carabinieri Lugano. Eine der ältesten Sportgesellschaften des Tessins mit über 400 Mitgliedern.",
    lat: 46.004,
    lng: 8.951,
  },
  {
    id: "ti-2",
    name: "Società di tiro Bellinzona",
    kanton: "TI",
    ortschaft: "Bellinzona",
    disziplinen: ["300m"],
    neumitglieder: true,
    beschreibung: "Gegründet 1889 als Società Carabinieri di Bellinzona. Seit über 130 Jahren aktiv, hat Schützen bis zu Olympischen Spielen hervorgebracht.",
    lat: 46.196,
    lng: 9.024,
  },

  // ─── KANTON WAADT ───────────────────────────────────────
  {
    id: "vd-1",
    name: "Société de tir de Lausanne",
    kanton: "VD",
    ortschaft: "Lausanne",
    disziplinen: ["300m", "Pistole"],
    neumitglieder: true,
    beschreibung: "Traditionsreiche Schützengesellschaft in Lausanne, schiesst auf der Anlage Vernand auf 300m. Pistolenteams mehrfach Schweizer Meister.",
    lat: 46.520,
    lng: 6.634,
  },
  {
    id: "vd-2",
    name: "Société de tir de Vevey",
    kanton: "VD",
    ortschaft: "Vevey",
    disziplinen: ["300m"],
    neumitglieder: true,
    beschreibung: "Gegründet 1898 als Francs-Tireurs de Vevey. Pflegt den traditionellen Schiesssport mit Ordonnanzwaffen auf 300 Meter.",
    lat: 46.462,
    lng: 6.843,
  },

  // ─── KANTON GENF ────────────────────────────────────────
  {
    id: "ge-1",
    name: "Société de tir de Genève",
    kanton: "GE",
    ortschaft: "Genf",
    disziplinen: ["300m", "Pistole"],
    neumitglieder: true,
    beschreibung: "Ursprünge vor 1474. Eine der ältesten Schützengesellschaften der Schweiz und heute zahlenmässig eine der grössten des Landes.",
    lat: 46.205,
    lng: 6.144,
  },

  // ─── KANTON NEUENBURG ───────────────────────────────────
  {
    id: "ne-1",
    name: "Société de tir de Neuchâtel",
    kanton: "NE",
    ortschaft: "Neuenburg",
    disziplinen: ["300m"],
    neumitglieder: true,
    beschreibung: "Schützentradition seit 1406. Die heutige Société Neuchâteloise de Tir Sportif entstand 2003 aus der Fusion dreier kantonaler Schützenverbände.",
    lat: 46.992,
    lng: 6.931,
  },

  // ─── KANTON SCHAFFHAUSEN ────────────────────────────────
  {
    id: "sh-1",
    name: "Schützengesellschaft Schaffhausen",
    kanton: "SH",
    ortschaft: "Schaffhausen",
    disziplinen: ["300m", "Pistole"],
    neumitglieder: true,
    beschreibung: "Um 1443 gegründet. Eine der ältesten Schützengesellschaften der Schweiz — bereits 1537 wurde am heutigen Standort ein erstes Schützenhaus errichtet.",
    lat: 47.697,
    lng: 8.635,
  },

  // ─── KANTON THURGAU ─────────────────────────────────────
  {
    id: "tg-1",
    name: "Schützenverein Frauenfeld",
    kanton: "TG",
    ortschaft: "Frauenfeld",
    disziplinen: ["300m", "Pistole"],
    neumitglieder: true,
    beschreibung: "Frauenfeld war 2005 Austragungsort des Eidgenössischen Schützenfestes.",
    lat: 47.557,
    lng: 8.898,
  },

  // ─── KANTON SCHWYZ ──────────────────────────────────────
  {
    id: "sz-1",
    name: "Schützengesellschaft Schwyz",
    kanton: "SZ",
    ortschaft: "Schwyz",
    disziplinen: ["300m"],
    neumitglieder: true,
    beschreibung: "Traditionsreicher Verein im Urkanton Schwyz mit 300m-Gewehr und aktivem Jungschützenprogramm.",
    lat: 47.021,
    lng: 8.658,
  },

  // ─── KANTON URI ─────────────────────────────────────────
  {
    id: "ur-1",
    name: "Schützengesellschaft Altdorf",
    kanton: "UR",
    ortschaft: "Altdorf",
    disziplinen: ["300m"],
    neumitglieder: true,
    beschreibung: "Traditionsreicher Verein im Kanton Uri, Heimat von Wilhelm Tell.",
    lat: 46.881,
    lng: 8.644,
  },

  // ─── KANTON OBWALDEN ────────────────────────────────────
  {
    id: "ow-1",
    name: "Feldschützen Sarnen",
    kanton: "OW",
    ortschaft: "Sarnen",
    disziplinen: ["300m", "Feldschiessen"],
    neumitglieder: true,
    lat: 46.896,
    lng: 8.245,
  },

  // ─── KANTON NIDWALDEN ───────────────────────────────────
  {
    id: "nw-1",
    name: "Schützenverein Stans",
    kanton: "NW",
    ortschaft: "Stans",
    disziplinen: ["300m"],
    neumitglieder: true,
    lat: 46.959,
    lng: 8.366,
  },

  // ─── KANTON GLARUS ──────────────────────────────────────
  {
    id: "gl-1",
    name: "Schützengesellschaft Glarus",
    kanton: "GL",
    ortschaft: "Glarus",
    disziplinen: ["300m"],
    neumitglieder: true,
    lat: 47.041,
    lng: 9.068,
  },

  // ─── KANTON ZUG ─────────────────────────────────────────
  {
    id: "zg-1",
    name: "Schützengesellschaft Zug",
    kanton: "ZG",
    ortschaft: "Zug",
    disziplinen: ["300m", "Pistole"],
    neumitglieder: true,
    lat: 47.167,
    lng: 8.516,
  },

  // ─── KANTON APPENZELL AR ────────────────────────────────
  {
    id: "ar-1",
    name: "Schützenverein Herisau",
    kanton: "AR",
    ortschaft: "Herisau",
    disziplinen: ["300m"],
    neumitglieder: true,
    lat: 47.386,
    lng: 9.279,
  },

  // ─── KANTON APPENZELL AI ────────────────────────────────
  {
    id: "ai-1",
    name: "Schützengesellschaft Appenzell",
    kanton: "AI",
    ortschaft: "Appenzell",
    disziplinen: ["300m"],
    neumitglieder: true,
    lat: 47.331,
    lng: 9.409,
  },

  // ─── KANTON JURA ────────────────────────────────────────
  {
    id: "ju-1",
    name: "Société de tir de Delémont",
    kanton: "JU",
    ortschaft: "Delémont",
    disziplinen: ["300m"],
    neumitglieder: true,
    lat: 47.365,
    lng: 7.345,
  },

  // ─── ÜBERREGIONAL / DACHVERBÄNDE ────────────────────────
  {
    id: "ch-1",
    name: "Historische Schützen Schweiz",
    kanton: "BE",
    ortschaft: "Schweizweit",
    disziplinen: ["Historisches Schiessen"],
    website: "https://hischuetzen.ch",
    neumitglieder: true,
    beschreibung: "Dachverband der historischen Schützen. Organisiert Wettkämpfe mit historischen Waffen (Vetterli, K31 etc.).",
    lat: 46.948,
    lng: 7.447,
  },

  // ─── ERGÄNZUNGEN ───────────────────────────────────────────
  {
    id: "ai-2",
    name: "Pistolenschützen Appenzell",
    kanton: "AI",
    ortschaft: "Appenzell",
    disziplinen: ["Pistole", "25m", "50m", "Luftgewehr"],
    website: "https://www.ps-appenzell.ch",
    neumitglieder: true,
    beschreibung: "Pistolenschützenverein in Appenzell mit Luftpistole 10m, Sport- und Freipistole 25m/50m.",
    lat: 47.331,
    lng: 9.409,
  },
  {
    id: "ar-2",
    name: "Standschützen Teufen",
    kanton: "AR",
    ortschaft: "Teufen",
    disziplinen: ["300m", "Pistole", "50m", "25m"],
    website: "https://www.zielen.ch",
    neumitglieder: true,
    beschreibung: "Traditionsreicher Schiessverein in Teufen AR mit 300m-Gewehr und Pistolensektion.",
    lat: 47.394,
    lng: 9.380,
  },
  {
    id: "ge-2",
    name: "Exercices de l'Arquebuse et de la Navigation",
    kanton: "GE",
    ortschaft: "Petit-Lancy",
    disziplinen: ["300m", "Pistole", "50m", "25m"],
    website: "https://www.arquebuse.ch",
    neumitglieder: true,
    beschreibung: "Gegründet 1856. Historische Genfer Schiessgesellschaft mit Schiessschule und Stand in Petit-Lancy.",
    lat: 46.195,
    lng: 6.116,
  },
  {
    id: "gl-2",
    name: "Sportschützen Glarnerland",
    kanton: "GL",
    ortschaft: "Näfels",
    disziplinen: ["50m", "Luftgewehr"],
    website: "https://www.sportschuetzen-gl.ch",
    neumitglieder: true,
    beschreibung: "Einziger Glarner Verein in der Nationalliga A Luftgewehr, mit 10m- und 50m-Ständen.",
    lat: 47.100,
    lng: 9.065,
  },
  {
    id: "ju-2",
    name: "Société de Tir Porrentruy - La Campagne",
    kanton: "JU",
    ortschaft: "Porrentruy",
    disziplinen: ["300m", "Pistole", "25m", "50m"],
    website: "https://porrentruycampagne.ch",
    neumitglieder: true,
    beschreibung: "Schiessgesellschaft der Ajoie-Region mit 300m-Gewehr und Pistole 25m/50m.",
    lat: 47.415,
    lng: 7.075,
  },
  {
    id: "ne-2",
    name: "Société Neuchâteloise de Tir Pratique (SNTP)",
    kanton: "NE",
    ortschaft: "Neuenburg",
    disziplinen: ["IPSC", "Pistole"],
    website: "https://www.sntp.info",
    neumitglieder: true,
    beschreibung: "1986 gegründeter Verein für dynamisches Schiessen (IPSC) im Kanton Neuenburg.",
    lat: 46.992,
    lng: 6.931,
  },
  {
    id: "nw-2",
    name: "Schützengesellschaft Buochs",
    kanton: "NW",
    ortschaft: "Buochs",
    disziplinen: ["300m", "Feldschiessen"],
    website: "https://www.sg-buochs.ch",
    neumitglieder: true,
    beschreibung: "Traditionsverein in Buochs mit 300m-Schiessstand und aktiver Jungschützenausbildung.",
    lat: 46.974,
    lng: 8.421,
  },
  {
    id: "ow-2",
    name: "Pistolenschützen Sarnen",
    kanton: "OW",
    ortschaft: "Sarnen",
    disziplinen: ["Pistole", "25m", "50m"],
    website: "https://www.ps-sarnen.ch",
    neumitglieder: true,
    beschreibung: "1961 gegründeter Pistolenschiessverein in Sarnen mit Disziplinen Pistole 25m und 50m.",
    lat: 46.896,
    lng: 8.245,
  },
  {
    id: "sh-2",
    name: "Pistolenschützen Randen Schaffhausen",
    kanton: "SH",
    ortschaft: "Schaffhausen",
    disziplinen: ["Pistole", "25m", "50m"],
    website: "https://www.psranden.ch",
    neumitglieder: true,
    beschreibung: "Aktiver Pistolenschiessverein in Schaffhausen mit Sportpistole auf allen Distanzen.",
    lat: 47.697,
    lng: 8.635,
  },
  {
    id: "sz-2",
    name: "Sportschützen Einsiedeln",
    kanton: "SZ",
    ortschaft: "Einsiedeln",
    disziplinen: ["50m", "Luftgewehr"],
    website: "https://www.sportschuetzeneinsiedeln.ch",
    neumitglieder: true,
    beschreibung: "Sportschützenverein mit Kleinkaliber 50m und Luftgewehr 10m am Schiessstand Wäni.",
    lat: 47.128,
    lng: 8.748,
  },
  {
    id: "tg-2",
    name: "Schützenverein Kreuzlingen",
    kanton: "TG",
    ortschaft: "Kreuzlingen",
    disziplinen: ["300m", "Pistole", "50m", "Luftgewehr"],
    website: "https://www.sv-kreuzlingen.ch",
    neumitglieder: true,
    beschreibung: "Drei Abteilungen: Gewehr 300m, Pistole und Gewehr 50m/10m. Aktiver Schiessverein am Bodensee.",
    lat: 47.650,
    lng: 9.175,
  },
  {
    id: "tg-3",
    name: "Schützengesellschaft Weinfelden",
    kanton: "TG",
    ortschaft: "Weinfelden",
    disziplinen: ["300m", "Pistole", "50m", "25m"],
    website: "https://www.sgweinfelden.ch",
    neumitglieder: true,
    beschreibung: "Betreibt das Schiesssportzentrum Hau in Weinfelden mit 300m-Gewehr und Pistolensektion.",
    lat: 47.567,
    lng: 9.107,
  },
  {
    id: "zg-2",
    name: "Schiesssportverein Cham-Ennetsee",
    kanton: "ZG",
    ortschaft: "Cham",
    disziplinen: ["300m", "50m", "Pistole", "Luftgewehr"],
    website: "https://ssvcham-ennetsee.ch",
    neumitglieder: true,
    beschreibung: "2007 aus fünf Vereinen fusioniert, mit Wurzeln bis 1694. Schiesssport auf 300m, 50m, 25m und 10m.",
    lat: 47.182,
    lng: 8.463,
  },
  {
    id: "vd-3",
    name: "Société des Carabiniers de Lausanne",
    kanton: "VD",
    ortschaft: "Lausanne",
    disziplinen: ["300m", "Feldschiessen"],
    website: "https://www.carabiniers-lausanne.ch",
    neumitglieder: true,
    beschreibung: "Gegründet 1825. Traditionsreiche Karabiniergesellschaft in Lausanne mit obligatorischem und Feldschiessen.",
    lat: 46.520,
    lng: 6.634,
  },
  {
    id: "be-10",
    name: "CSCS Laupen (IPSC Club)",
    kanton: "BE",
    ortschaft: "Laupen",
    disziplinen: ["IPSC"],
    website: "https://www.cscsl.ch",
    neumitglieder: true,
    beschreibung: "IPSC-Club in der Region Bern mit Indoor-Training und Outdoor-Matches.",
    lat: 46.900,
    lng: 7.240,
  },
  {
    id: "so-3",
    name: "Dynamische Schützen Falkenstein",
    kanton: "SO",
    ortschaft: "Niederbipp",
    disziplinen: ["IPSC"],
    website: "https://dsfalkenstein.ch",
    neumitglieder: true,
    beschreibung: "IPSC-Verein in Niederbipp, bekannt für die Organisation des Juratreff-Matchs.",
    lat: 47.269,
    lng: 7.695,
  },
  {
    id: "be-11",
    name: "Société de tir Bienne",
    kanton: "BE",
    ortschaft: "Biel/Bienne",
    disziplinen: ["300m", "Pistole", "25m"],
    website: "https://www.tir-bienne.ch",
    neumitglieder: true,
    beschreibung: "Bilingue Schiessgesellschaft in Biel mit 300m-Stand und 25m-Pistolenstand.",
    lat: 47.137,
    lng: 7.247,
  },

  // ─── NEUE VEREINE AUS KANTONSVERBÄNDEN ────────────────────

  // ─── KANTON ZÜRICH (aus ZHSV-Verzeichnis) ────────────────
  {
    id: "zh-11",
    name: "Schützengesellschaft Horgen",
    kanton: "ZH",
    ortschaft: "Horgen",
    disziplinen: ["300m", "Feldschiessen"],
    website: "https://www.sghorgen.ch",
    neumitglieder: true,
    beschreibung: "Traditionsreiche Schützengesellschaft am Zürichsee mit 300m-Schiessstand.",
    lat: 47.259,
    lng: 8.598,
  },
  {
    id: "zh-12",
    name: "Pistolenschiessverein Wädenswil",
    kanton: "ZH",
    ortschaft: "Wädenswil",
    disziplinen: ["Pistole", "25m", "50m"],
    website: "https://www.psv-waedenswil.ch",
    neumitglieder: true,
    beschreibung: "Pistolenschiessverein in Wädenswil mit 25m- und 50m-Pistolenständen.",
    lat: 47.231,
    lng: 8.672,
  },
  {
    id: "zh-13",
    name: "Schützengesellschaft Stäfa",
    kanton: "ZH",
    ortschaft: "Stäfa",
    disziplinen: ["300m", "Feldschiessen"],
    website: "https://www.sgstaefa.ch",
    neumitglieder: true,
    beschreibung: "Aktive Schützengesellschaft in Stäfa am Zürichsee.",
    lat: 47.243,
    lng: 8.726,
  },
  {
    id: "zh-14",
    name: "Schiesssportverein Illnau-Effretikon",
    kanton: "ZH",
    ortschaft: "Illnau-Effretikon",
    disziplinen: ["300m", "Pistole", "50m"],
    website: "https://www.ssvie.ch",
    neumitglieder: true,
    beschreibung: "Schiesssportverein im Zürcher Oberland mit Gewehr- und Pistolensektion.",
    lat: 47.413,
    lng: 8.730,
  },
  {
    id: "zh-15",
    name: "Pistolenschützen Kloten",
    kanton: "ZH",
    ortschaft: "Kloten",
    disziplinen: ["Pistole", "25m", "50m"],
    website: "https://www.pskloten.ch",
    neumitglieder: true,
    beschreibung: "Pistolenschützenverein in Kloten mit breitem Angebot.",
    lat: 47.451,
    lng: 8.585,
  },
  {
    id: "zh-16",
    name: "Schützengesellschaft Dübendorf",
    kanton: "ZH",
    ortschaft: "Dübendorf",
    disziplinen: ["300m", "Pistole"],
    website: "https://www.stsduebi.ch",
    neumitglieder: true,
    beschreibung: "Stadtschützen Dübendorf mit Gewehr- und Pistolenschiessen.",
    lat: 47.397,
    lng: 8.618,
  },
  {
    id: "zh-17",
    name: "Schützenverein Adliswil",
    kanton: "ZH",
    ortschaft: "Adliswil",
    disziplinen: ["300m", "Feldschiessen"],
    website: "https://www.svadliswil.ch",
    neumitglieder: true,
    beschreibung: "Schützenverein in Adliswil am Fusse des Uetliberg.",
    lat: 47.311,
    lng: 8.527,
  },

  // ─── KANTON AARGAU (aus AGSV-Verzeichnis) ────────────────
  {
    id: "ag-4",
    name: "Schützengesellschaft Lenzburg",
    kanton: "AG",
    ortschaft: "Lenzburg",
    disziplinen: ["300m", "Pistole", "Feldschiessen"],
    website: "https://www.sg-lenzburg.ch",
    neumitglieder: true,
    beschreibung: "Traditionsverein in Lenzburg mit Gewehr- und Pistolenschiessen.",
    lat: 47.388,
    lng: 8.175,
  },
  {
    id: "ag-5",
    name: "Schiesssportgesellschaft Brugg-Windisch",
    kanton: "AG",
    ortschaft: "Brugg",
    disziplinen: ["300m", "Pistole"],
    website: "https://www.ssg-brugg-windisch.ch",
    neumitglieder: true,
    beschreibung: "Schiesssportgesellschaft im Raum Brugg-Windisch.",
    lat: 47.486,
    lng: 8.208,
  },
  {
    id: "ag-6",
    name: "Sportschützen Muhen",
    kanton: "AG",
    ortschaft: "Muhen",
    disziplinen: ["50m", "Luftgewehr", "Pistole"],
    website: "https://www.sportschuetzen-muhen.ch",
    neumitglieder: true,
    beschreibung: "Erfolgreicher Sportschützenverein mit starkem Nachwuchsprogramm.",
    lat: 47.337,
    lng: 8.057,
  },
  {
    id: "ag-7",
    name: "Schützengesellschaft Zofingen",
    kanton: "AG",
    ortschaft: "Zofingen",
    disziplinen: ["300m", "Pistole", "Feldschiessen"],
    website: "https://www.sgzofingen.ch",
    neumitglieder: true,
    beschreibung: "Schützengesellschaft in der Altstadt von Zofingen.",
    lat: 47.289,
    lng: 7.946,
  },
  {
    id: "ag-8",
    name: "Schiesssportverein Obersiggenthal",
    kanton: "AG",
    ortschaft: "Obersiggenthal",
    disziplinen: ["300m", "Pistole", "50m"],
    website: "https://www.ssv-obersiggenthal.ch",
    neumitglieder: true,
    beschreibung: "Aktiver Verein mit Jugendförderung im Raum Baden-Siggenthal.",
    lat: 47.489,
    lng: 8.326,
  },
  {
    id: "ag-9",
    name: "Pistolenclub Fahrwangen",
    kanton: "AG",
    ortschaft: "Fahrwangen",
    disziplinen: ["Pistole", "25m", "50m"],
    website: "https://www.pcfahrwangen.ch",
    neumitglieder: true,
    beschreibung: "Pistolenschützenverein im Seetal.",
    lat: 47.291,
    lng: 8.237,
  },

  // ─── KANTON LUZERN (aus LKSV-Verzeichnis) ─────────────────
  {
    id: "lu-4",
    name: "Schützengesellschaft Kriens",
    kanton: "LU",
    ortschaft: "Kriens",
    disziplinen: ["300m", "Feldschiessen"],
    website: "https://www.sg-kriens.ch",
    neumitglieder: true,
    beschreibung: "Schützengesellschaft in der Agglomeration Luzern.",
    lat: 47.034,
    lng: 8.276,
  },
  {
    id: "lu-5",
    name: "Schützengesellschaft Sempach",
    kanton: "LU",
    ortschaft: "Sempach",
    disziplinen: ["300m", "Feldschiessen"],
    website: "https://www.sgsempach.ch",
    neumitglieder: true,
    beschreibung: "Schützengesellschaft in der historischen Schlachtstadt Sempach.",
    lat: 47.133,
    lng: 8.190,
  },
  {
    id: "lu-6",
    name: "Pistolenschützen Willisau",
    kanton: "LU",
    ortschaft: "Willisau",
    disziplinen: ["Pistole", "25m", "50m"],
    website: "https://www.pswillisau.ch",
    neumitglieder: true,
    beschreibung: "Pistolenschützenverein im Luzerner Hinterland.",
    lat: 47.121,
    lng: 7.993,
  },
  {
    id: "lu-7",
    name: "Schützengesellschaft Rothenburg",
    kanton: "LU",
    ortschaft: "Rothenburg",
    disziplinen: ["300m"],
    website: "https://www.sgrothenburg.ch",
    neumitglieder: true,
    beschreibung: "Aktiver Schiessverein in Rothenburg bei Luzern.",
    lat: 47.090,
    lng: 8.270,
  },

  // ─── KANTON SOLOTHURN (aus SOSV-Verzeichnis) ───────────────
  {
    id: "so-4",
    name: "Schützengesellschaft der Stadt Solothurn",
    kanton: "SO",
    ortschaft: "Solothurn",
    disziplinen: ["300m", "Pistole"],
    website: "https://www.sgsso.ch",
    neumitglieder: true,
    beschreibung: "Städtische Schützengesellschaft in der Barockstadt Solothurn.",
    lat: 47.209,
    lng: 7.532,
  },
  {
    id: "so-5",
    name: "Stadtschützen Olten",
    kanton: "SO",
    ortschaft: "Olten",
    disziplinen: ["300m", "Pistole", "Feldschiessen"],
    website: "https://www.stadtschuetzen-olten.ch",
    neumitglieder: true,
    beschreibung: "Traditionsreiche Stadtschützen in Olten mit aktivem Vereinsleben.",
    lat: 47.350,
    lng: 7.907,
  },
  {
    id: "so-6",
    name: "Schützengesellschaft Biberist",
    kanton: "SO",
    ortschaft: "Biberist",
    disziplinen: ["300m", "Feldschiessen"],
    website: "https://www.schuetzen-biberist.ch",
    neumitglieder: true,
    beschreibung: "Schützengesellschaft in Biberist bei Solothurn.",
    lat: 47.178,
    lng: 7.562,
  },
  {
    id: "so-7",
    name: "Luftgewehrschützen Olten",
    kanton: "SO",
    ortschaft: "Olten",
    disziplinen: ["Luftgewehr"],
    website: "http://www.lgolten.ch",
    neumitglieder: true,
    beschreibung: "Spezialisierter Verein für Luftgewehrschiessen 10m in Olten.",
    lat: 47.350,
    lng: 7.907,
  },

  // ─── KANTON BASEL-LANDSCHAFT (aus SVRB-Verzeichnis) ────────
  {
    id: "bl-3",
    name: "Schützengesellschaft Muttenz",
    kanton: "BL",
    ortschaft: "Muttenz",
    disziplinen: ["300m", "Feldschiessen"],
    website: "https://www.sgmuttenz.ch",
    neumitglieder: true,
    beschreibung: "Schützengesellschaft im Basler Vorort Muttenz.",
    lat: 47.522,
    lng: 7.645,
  },
  {
    id: "bl-4",
    name: "Schützengesellschaft Reinach BL",
    kanton: "BL",
    ortschaft: "Reinach",
    disziplinen: ["300m", "Pistole"],
    website: "https://www.sg-reinach.ch",
    neumitglieder: true,
    beschreibung: "Schützengesellschaft im Birseck bei Basel.",
    lat: 47.494,
    lng: 7.591,
  },
  {
    id: "bl-5",
    name: "Schützengesellschaft Pratteln",
    kanton: "BL",
    ortschaft: "Pratteln",
    disziplinen: ["300m", "Feldschiessen"],
    website: "https://sgpratteln.clubdesk.com",
    neumitglieder: true,
    beschreibung: "Schützengesellschaft in Pratteln bei Basel.",
    lat: 47.521,
    lng: 7.693,
  },
  {
    id: "bl-6",
    name: "Schützengesellschaft Gelterkinden",
    kanton: "BL",
    ortschaft: "Gelterkinden",
    disziplinen: ["300m"],
    website: "https://www.sggelterkinden.ch",
    neumitglieder: true,
    beschreibung: "Schützengesellschaft im Oberbaselbiet.",
    lat: 47.463,
    lng: 7.856,
  },
  {
    id: "bs-3",
    name: "Feldschützenverein Basel",
    kanton: "BS",
    ortschaft: "Basel",
    disziplinen: ["300m", "Feldschiessen"],
    website: "https://www.fsv-basel.ch",
    neumitglieder: true,
    beschreibung: "Feldschützenverein in Basel-Stadt mit Schwerpunkt 300m-Gewehr.",
    lat: 47.560,
    lng: 7.589,
  },

  // ─── KANTON THURGAU (aus TKSV-Verzeichnis) ────────────────
  {
    id: "tg-4",
    name: "Stadtschützen Bischofszell",
    kanton: "TG",
    ortschaft: "Bischofszell",
    disziplinen: ["300m", "Feldschiessen"],
    email: "info@ssbzell.ch",
    neumitglieder: true,
    beschreibung: "Stadtschützen in der historischen Rosenstadt Bischofszell.",
    lat: 47.496,
    lng: 9.241,
  },
  {
    id: "tg-5",
    name: "Pistolenschützen Arbon",
    kanton: "TG",
    ortschaft: "Arbon",
    disziplinen: ["Pistole", "25m", "50m"],
    website: "https://pistolenschuetzen.ch",
    neumitglieder: true,
    beschreibung: "Pistolenschützenverein in Arbon am Bodensee.",
    lat: 47.516,
    lng: 9.432,
  },
  {
    id: "tg-6",
    name: "Stadtschützengesellschaft Frauenfeld",
    kanton: "TG",
    ortschaft: "Frauenfeld",
    disziplinen: ["300m", "Pistole", "Feldschiessen"],
    website: "https://www.ssgf.ch",
    neumitglieder: true,
    beschreibung: "Grosse Stadtschützengesellschaft in der Thurgauer Kantonshauptstadt.",
    lat: 47.557,
    lng: 8.898,
  },

  // ─── KANTON GRAUBÜNDEN (aus KBSV-Verzeichnis) ─────────────
  {
    id: "gr-3",
    name: "Schiesssport Davos",
    kanton: "GR",
    ortschaft: "Davos",
    disziplinen: ["300m", "Pistole", "50m", "25m"],
    website: "https://www.schiesssport-davos.ch",
    neumitglieder: true,
    beschreibung: "Breit aufgestellter Schiesssportverein im Kurort Davos mit 300m, 50m und 25m.",
    lat: 46.800,
    lng: 9.836,
  },
  {
    id: "gr-4",
    name: "Schiesssportverein Igis-Landquart",
    kanton: "GR",
    ortschaft: "Igis",
    disziplinen: ["300m", "Pistole"],
    website: "https://www.schiesssportverein-igis-landquart.ch",
    neumitglieder: true,
    beschreibung: "Schiesssportverein in der Region Landquart mit Gewehr und Pistole.",
    lat: 46.946,
    lng: 9.573,
  },
  {
    id: "gr-5",
    name: "Vereinigte Schützengesellschaft St. Luzisteig",
    kanton: "GR",
    ortschaft: "Maienfeld",
    disziplinen: ["300m", "Feldschiessen"],
    website: "https://www.vsgl.ch",
    neumitglieder: true,
    beschreibung: "Schützengesellschaft am historischen Passübergang St. Luzisteig bei Maienfeld.",
    lat: 47.003,
    lng: 9.527,
  },
  {
    id: "gr-6",
    name: "Sportschützen Domat/Ems",
    kanton: "GR",
    ortschaft: "Domat/Ems",
    disziplinen: ["50m", "Luftgewehr"],
    website: "https://www.sportschuetzen-domatems.ch",
    neumitglieder: true,
    beschreibung: "Sportschützenverein in Domat/Ems mit 50m-Kleinkaliber und 10m-Luftgewehr.",
    lat: 46.834,
    lng: 9.451,
  },

  // ─── KANTON ZUG (aus Zuger KSV-Verzeichnis) ───────────────
  {
    id: "zg-3",
    name: "Schützengesellschaft der Stadt Baar",
    kanton: "ZG",
    ortschaft: "Baar",
    disziplinen: ["300m", "Feldschiessen"],
    website: "https://www.sgbaar.ch",
    neumitglieder: true,
    beschreibung: "Schützengesellschaft in Baar, der grössten Gemeinde des Kantons Zug.",
    lat: 47.196,
    lng: 8.527,
  },
  {
    id: "zg-4",
    name: "Pistolenschützen Baar",
    kanton: "ZG",
    ortschaft: "Baar",
    disziplinen: ["Pistole", "25m", "50m"],
    website: "https://www.pistolenschuetzenbaar.ch",
    neumitglieder: true,
    beschreibung: "Pistolenschiessverein in Baar mit 25m- und 50m-Ständen.",
    lat: 47.196,
    lng: 8.527,
  },
  {
    id: "zg-5",
    name: "Schützen Ägerital-Morgarten",
    kanton: "ZG",
    ortschaft: "Unterägeri",
    disziplinen: ["300m", "Feldschiessen"],
    website: "https://www.schuetzen-aegerital-morgarten.ch",
    neumitglieder: true,
    beschreibung: "Schiessverein im historischen Ägerital, Schauplatz der Schlacht am Morgarten.",
    lat: 47.137,
    lng: 8.588,
  },
  {
    id: "zg-6",
    name: "Schützengesellschaft Steinhausen",
    kanton: "ZG",
    ortschaft: "Steinhausen",
    disziplinen: ["300m"],
    website: "https://www.sgsteinhausen.ch",
    neumitglieder: true,
    beschreibung: "Schützengesellschaft in Steinhausen bei Zug.",
    lat: 47.196,
    lng: 8.490,
  },

  // ─── KANTON URI (aus KSVU-Verzeichnis) ─────────────────────
  {
    id: "ur-2",
    name: "Schützenverein Gotthard Andermatt",
    kanton: "UR",
    ortschaft: "Andermatt",
    disziplinen: ["300m"],
    neumitglieder: true,
    beschreibung: "Schiessverein in Andermatt am Fusse des Gotthardpasses.",
    lat: 46.636,
    lng: 8.594,
  },
  {
    id: "ur-3",
    name: "Pistolenschützen Altdorf-Erstfeld",
    kanton: "UR",
    ortschaft: "Altdorf",
    disziplinen: ["Pistole", "25m", "50m"],
    neumitglieder: true,
    beschreibung: "Pistolenschützenverein im unteren Reusstal.",
    lat: 46.881,
    lng: 8.644,
  },

  // ─── KANTON SCHWYZ (Ergänzungen) ──────────────────────────
  {
    id: "sz-3",
    name: "Schützengesellschaft Lachen",
    kanton: "SZ",
    ortschaft: "Lachen",
    disziplinen: ["300m", "Pistole"],
    neumitglieder: true,
    beschreibung: "Schützengesellschaft am oberen Zürichsee in der March.",
    lat: 47.194,
    lng: 8.853,
  },
];

export const ALLE_KANTONE = [
  { id: "", label: "Alle Kantone" },
  { id: "AG", label: "Aargau" },
  { id: "AI", label: "Appenzell AI" },
  { id: "AR", label: "Appenzell AR" },
  { id: "BE", label: "Bern" },
  { id: "BL", label: "Basel-Landschaft" },
  { id: "BS", label: "Basel-Stadt" },
  { id: "FR", label: "Freiburg" },
  { id: "GE", label: "Genf" },
  { id: "GL", label: "Glarus" },
  { id: "GR", label: "Graubünden" },
  { id: "JU", label: "Jura" },
  { id: "LU", label: "Luzern" },
  { id: "NE", label: "Neuenburg" },
  { id: "NW", label: "Nidwalden" },
  { id: "OW", label: "Obwalden" },
  { id: "SG", label: "St. Gallen" },
  { id: "SH", label: "Schaffhausen" },
  { id: "SO", label: "Solothurn" },
  { id: "SZ", label: "Schwyz" },
  { id: "TG", label: "Thurgau" },
  { id: "TI", label: "Tessin" },
  { id: "UR", label: "Uri" },
  { id: "VD", label: "Waadt" },
  { id: "VS", label: "Wallis" },
  { id: "ZG", label: "Zug" },
  { id: "ZH", label: "Zürich" },
];

export const ALLE_DISZIPLINEN = [
  "300m",
  "Pistole",
  "50m",
  "25m",
  "Luftgewehr",
  "IPSC",
  "IDPA",
  "Feldschiessen",
  "Jagdschiessen",
  "Historisches Schiessen",
];
